#!/bin/bash
sudo systemctl stop celery
redis-cli keys "celery*" | xargs redis-cli DEL
redis-cli keys "celery*" | xargs redis-cli DEL
redis-cli keys "celery*" | xargs redis-cli DEL
redis-cli keys "celery*" | xargs redis-cli DEL
redis-cli keys "celery*" | xargs redis-cli DEL
redis-cli keys "celery*" | xargs redis-cli DEL
sudo systemctl start celery
